###
GET http://localhost:8080/clientes/5/extrato

###
GET http://localhost:8080/clientes/5/extrato_antigo

###

POST  http://localhost:8080/clientes/5/transacoes
content-type: application/json

{
    "valor": 1,
    "tipo" : "d",
    "descricao" : "descricao"
}